name: CI Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.
          cache: 'npm'

      - name: Install dependencies 
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Run Tests
        run: npm run test 

      - name: Build the project
        run: npm run build
  publish-docker:
    runs-on: ubuntu-latest
    needs: build-npm

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: gabrielpacificooo/grotrack:${{ secrets.DOCKERHUB_IMAGE_TAG}}
